# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

markdown : kramdown
highlighter: rouge
permalink:           pretty
rdiscount:
  extensions: [smart]

# Setup
title:               Yash Upadhyay
tagline:             'learn to tech machines'
description:         'helping beginners understand AI better'
url:                 redhood95.github.io
baseurl:             'https://redhood95.github.io'
paginate:            5
paginate_path:       "page:num"
excerpt_separator:   <!--more-->
# Footer Links
footer-links:
  dribbble:
  email: yashup1997@gmail.com
  facebook: 
  flickr:
  github: github.com/redhood95
  instagram:
  linkedin: https://www.linkedin.com/in/yash-u-a64bb8101/
# About/contact
author:
  name:              Yash Upadhyay
  url:              https://redhood95.github.io
  email:             yashup1997@gmail.com

# Custom vars
version:             1.1.0
